networks:
  loki:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

services:
  gateway:
    build: ./gateway
    container_name: gateway_c
    ports:
      - 5900:5900
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    environment:
      - DISPLAY=$DISPLAY
    networks:
      loki:
        ipv4_address: 10.5.0.5


  icli:
    build: 
      context: ./icli
      args:
        - ICLI_IBKR_ACCOUNT_ID=${ICLI_IBKR_ACCOUNT_ID}
        - ICLI_IBKR_HOST=${ICLI_IBKR_HOST}
        - ICLI_IBKR_PORT=${ICLI_IBKR_PORT}
    container_name: icli_c
    networks:
      loki:
        ipv4_address: 10.5.0.6


  taras_trader:
    build: 
      context: ./taras_trader
      args:
        - ICLI_IBKR_ACCOUNT_ID=${ICLI_IBKR_ACCOUNT_ID}
        - ICLI_IBKR_HOST=${ICLI_IBKR_HOST}
        - ICLI_IBKR_PORT=${ICLI_IBKR_PORT}
    container_name: taras_trader_c
    volumes:
      - ./config/config_buy.yaml:/app/taras_trader/config_buy.yaml
    networks:
      loki:
        ipv4_address: 10.5.0.7


  config:
    build: ./config
    container_name: config_c
    volumes:
      - ./config/config_buy.yaml:/config_buy.yaml
    networks:
      loki:
        ipv4_address: 10.5.0.8
