networks:
  loki:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - 5900:5900
    networks:
      loki:
        ipv4_address: 10.5.0.5


  icli:
    build: ./icli
    container_name: icli
    networks:
      loki:
        ipv4_address: 10.5.0.6


  taras_trader:
    build: ./taras_trader
    container_name: taras_trader
    volumes:
      - ./config/config_buy.yaml:/app/taras_trader/config_buy.yaml
    networks:
      loki:
        ipv4_address: 10.5.0.7


  config:
    build: ./config
    container_name: config
    volumes:
      - ./config/config_buy.yaml:/config_buy.yaml
    networks:
      loki:
        ipv4_address: 10.5.0.8
