  10%:  # buy as a limit order
    TSLA  # todo: ask if this price is final or initial (e.g. buy on 2345 - 10%) and why it needs to be provided
    PSTG  
...
---
# milestone 3 (risk tolerancy mechanism for every stock)
cancel-stock-selling:  # some sort of retry mechanism. Needs specification how certain it must work, just manually type or process by algorithm 
  - AAPL
sell-stock-on-drop: 
  10%:  # sell as a limit order
    - TSLA
    - MSFT
  20%:  # sell as a limit order
    - AMD
...
---
# milestone 4 (stock multiplies in price and drops x percentages)
complex-condition:
  - x3 and drop 10%:  # ask if x is integer or might be fraction
    - TSLA  # check if stock is held for more than year and in such a case sell as a limit order otherwise ?(it's not possible that price in milestone 4
            #  is lower than in milestone 3 (if x is integer), so do nothing?)
...
---
# milestone 5
buy-stocks-on-margin:
  # need to calculate a margin? how often? where to output (icli has PnL field)?
  # how long to allow for a stock to underperform? Maybe when (loan - profit) reaches some number of it's initial purchase cost (e.g. 10%),
  # but that way it becomes milestone 2 
  - PSTG 
...


fill: "off"
order:
  buy:
    - stocks:
        - TSLA: 2
        - PSTG: 4
      conditions:
        - type: trailing-limit
        # - funds: 10000
          #- price-cents: 2000  # request current price
        - trailing-drop-percent: 10
    - stocks:
        - MSFT: 2
        - AAPL: 6
    - conditions:
        - type: trailing-limit
        # - funds: 10000
          #- price-cents: 2000  # request current price
        - trailing-drop-percent: 10
  sell:
    - type: trailing-limit
    - trailing-drop-percent: 20
    - margin-loss: 1


