fill: 'off'
order:
  buy:
  - stocks:
    - TSLA: 2
    conditions:
    - type: trailing-limit
    - trailing-drop-percent: 10
    - trailing-up-percent: 2
  - stocks:
    - MSFT: 2
    - AAPL: 6
    conditions:
    - type: trailing-limit
    - trailing-drop-percent: 10
    - trailing-up-percent: 2
  sell:
  - type: trailing-limit
  - trailing-drop-percent: 20
  - margin-loss: 1
